name: Continuous Delivery

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  create-qa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Decrypt Firebase and Google Services secrets
        run: | 
          chmod +x script/decrypt.sh
          script/decrypt.sh
        env:
          GOOGLE_SERVICES_KEY: ${{ secrets.GOOGLE_SERVICES_KEY }}
          FIREBASE_SERVICE_ACC: ${{ secrets.FIREBASE_SERVICE_ACC }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Debug APK and Distribute to Testers via Firebase
        run: ./gradlew assembleDebug appDistributionUploadDebug

  notify-qa:
    needs: create-qa-build
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C074WKL8J66'
          slack-message: "QA build created: ${{ github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_OAUTH_TOKEN }}
