name: Continuous Delivery

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  create-qa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Add secrets to google-services.json
        run: |
          sed -i 's/replace-with-firebase-key/${{ secrets.FIREBASE_KEY }}/g' app/google-services.json

#      - name: Add secrets to firebase-service-account.json
#        uses: MathieuSoysal/replace-string-in-file@v1.1.0
#        with:
#          file: app/firebase-service-account.json
#          old-string: replace-with-firebase-service-account-key-id
#          new-string: ${{ secrets.FIREBASE_SERVICE_ACC_KEY_ID }}
#          without-checkout: true
#
#      - name: Add secrets to firebase-service-account.json
#        uses: MathieuSoysal/replace-string-in-file@v1.1.0
#        with:
#          file: app/firebase-service-account.json
#          old-string: replace-with-firebase-service-account-key
#          new-string: ${{ secrets.FIREBASE_SERVICE_ACC_KEY }}
#          without-checkout: true
#
#      - name: Add secrets to firebase-service-account.json
#        uses: MathieuSoysal/replace-string-in-file@v1.1.0
#        with:
#          file: app/firebase-service-account.json
#          old-string: replace-with-firebase-service-account-client-id
#          new-string: ${{ secrets.FIREBASE_SERVICE_ACC_CLIENT_ID }}
#          without-checkout: true
#
#      - name: Add secrets to firebase-service-account.json
#        uses: MathieuSoysal/replace-string-in-file@v1.1.0
#        with:
#          file: app/firebase-service-account.json
#          old-string: replace-with-firebase-service-account-cert-url
#          new-string: ${{ secrets.FIREBASE_SERVICE_ACC_CERT_URL }}
#          without-checkout: true
#
#      - name: Generate Debug APK and Distribute to Testers via Firebase
#        run: ./gradlew assembleDebug appDistributionUploadDebug
#
#      - name: Send Slack Notification
#        id: slack
#        uses: slackapi/slack-github-action@v1.26.0
#        with:
#          channel-id: 'C074WKL8J66'
#          slack-message: "QA build created: ${{ github.event.head_commit.url }}"
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_OAUTH_TOKEN }}
