name: Gitleaks

on:
  repository_dispatch:
    types: [gitleaks-scan]
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * 1'

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}