name: Pull Request Reviewed

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notify-slack:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C074G37NZEK'
          slack-message: "Pull request ready for review: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN = ${{ secrets.SLACKBOT_OAUTH_TOKEN }}
